#!/usr/bin/env bash

# black background:
xsetroot -solid '#000000'
# move mouse to bottom right corner:
xdotool mousemove 10000 10000

# put all windows in fullscreen mode:
herbstclient rule fullscreen=on

# create desktops:
idx='-1'
for name in {1..5} ; do
    idx=$((idx+1))
    if ! herbstclient silent attr tags.${idx}.index ; then
        herbstclient add "$name"
    else
        herbstclient set_attr tags.${idx}.name "$name"
    fi
done

# herbstclient spawn ~/.config/herbstluftwm/

